### PR TITLE
Enable -Wshadow, starting fixing warnings

### PR DESCRIPTION
**Pull request by springmeyer**

### CODE REVIEW

**Comment by springmeyer** [comment]
@ericfischer - Here is one that is confusing:

```
geojson.c:1580:304: warning: declaration shadows a variable in the global scope [-Wshadow]
  ...*exclude, struct pool *include, int exclude_all, double droprate, int buffer, const char *tmpdir, double gamma, int *prevent, int *additional...
                                                                                                                          ^
geojson.c:48:12: note: previous declaration is here
static int prevent[256];
           ^
```

I tried renaming the `prevent` argument in the `read_json` function and that did not lead to a compile error or test failure (that I can see) so could this variable actually be unused or depending on the global?

**Comment by ericfischer** [comment]
Yes @springmeyer, it's a pointer to the (file-scope) global variable, so there's no actual need to be passing it as a parameter here.

**Comment by springmeyer** [comment]
@ericfischer ah, thanks, fixed in 451224a

**Comment by springmeyer** [comment]
hmm, breaking now with older g++-4.9: https://travis-ci.org/mapbox/tippecanoe/jobs/126174847#L268

```
geojson.c:122:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < nreader; i++) {
  ^
```

**Comment by springmeyer** [comment]
pausing on this branch, will wait for https://github.com/mapbox/tippecanoe/issues/231

**Comment by tmcw** [comment]
[Wshadow](https://github.com/mapbox/tippecanoe/blob/master/Makefile#L12) is now enabled in `master`, closing this branch.

**Pull request closed without merging**
