### PR TITLE
Record the command line options in the tileset metadata

### PR DESCRIPTION
**Pull request by ericfischer**
cc @ian29 @mapsam

### CODE REVIEW

**Comment by ian29** [comment]
so speedy

**Comment by mapsam** [comment]
Nice @ericfischer! Are commands with quotes `"` or `'` escaped properly?

**Comment by ericfischer** [comment]
@mapsam The only explicit escaping is of spaces and backslashes, which should be sufficient in the sqlite3 form. In the JSON form the strings get another level of escaping like anything else in the metadata. But you're right: I should escape all whitespace, not just spaces, because imaginably there could be a newline within the options.

**Comment by ericfischer** [comment]
Actually you're totally right @mapsam: I was thinking about JSON quoting, not shell quoting. I'll fix it today.

**Pull request merged**
