### PR TITLE
Use protozero for reading and writing vector tile protocol buffers

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by timiyay** [comment]
@ericfischer just to confirm, I can drop the `protobuf-c` dependency from the Homebrew formula now, right?

**Comment by ericfischer** [comment]
That's right, @timiyay, version 1.9.16 should no longer need that dependency. Thanks!

**Comment by timiyay** [comment]
@ericfischer The tests for the `tippecanoe` Homebrew formula are failing, now that I've removed the `protobuf-c` dep ([Jenkins link](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1007/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_tippecanoe/)):

```
clang++  -I/usr/local/include -I. -O3 -g -Wall  -std=c++11 -c decode.cc
decode.cc:13:10: fatal error: 'google/protobuf/io/zero_copy_stream_impl_lite.h' file not found
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
         ^
1 error generated.
make: *** [decode.o] Error 1
```

Are you able to shed any light on this issue? Perhaps I should keep the `protobuf-c` dependency for 1.9.16?

**Comment by ericfischer** [comment]
Sorry @timiyay, I accidentally left the dependency in place. This (among other things) is fixed in https://github.com/mapbox/tippecanoe/commit/bd5dc4ad181be85c6b00d28e204fafbf02934c7b (https://github.com/mapbox/tippecanoe/releases/tag/1.10.0).

**Comment by timiyay** [comment]
Thanks @ericfischer. I might cancel the brew formula for 1.9.16, then, and make a fresh one for 1.10.0.

**Comment by ericfischer** [comment]
Thanks @timiyay. I just pushed https://github.com/mapbox/tippecanoe/releases/tag/1.11.0 if you want to be even more up to the moment.

**Comment by timiyay** [comment]
OK no worries. I've made a new PR to update the Homebrew formula to 1.11.0: https://github.com/Homebrew/homebrew-core/pull/666

**Comment by ericfischer** [comment]
Thanks @timiyay!

**Pull request merged**
