### PR TITLE
Add an option for clustering features

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by mourner** [comment]
Wow @ericfischer. You're so fast! This will be such a killer feature. cc @kkaefer

**Comment by ericfischer** [comment]
Like everything else in Tippecanoe, it cheats by using quadkey intervals instead of actual distance measurements, but I hope it's close enough for most uses.

**Comment by ericfischer** [comment]
Pathological case:

https://gist.github.com/ericfischer/44f2a043d3bcec2940136acc4091f604

    tippecanoe -zg --cluster-densest-as-needed -O200 -f -o foo.mbtiles ../fail.json

gets stuck in a loop trying to make tile 8/199/121 work

**Comment by ericfischer** [comment]
The problem here was 615 points at exactly the same location, which were the only points in the tile.

**Comment by mourner** [comment]
Quick question, would it be possible to add an option to cluster with a fixed radius rather than a features-per-tile limit? No need to implement, just curious how much effort that would be and whether it makes sense.

**Comment by ericfischer** [comment]
What it's doing when trying to reduce the number of features per tile is trying to discover (the quadkey gap corresponding to) a distance that works, so there's no reason the distance couldn't be specified directly.

But does it really make sense to specify a single distance? I would think you would always want a large distance at low zooms, dropping down to a small distance at high zooms.

**Comment by mourner** [comment]
@ericfischer I'm just thinking that often you want visual consistency in the data for a certain appearance, e.g. you've carefully picked the radius to work well rendered as a heatmap layer. If the radius varies depending on which area the tile represents, it may lead to some unexpected results that are out of control. By fixed radius, I mean in tile coordinates, not geographic ones (so on z12, the same radius will represent 2x smaller real world distance than on z11). At least this is how Supercluster works.

**Comment by ericfischer** [comment]
OK, I'll take a look at what supercluster does. It should certainly be possible to use a fixed distance in tile coordinate terms.

**Comment by ericfischer** [comment]
OK, 4e7cc28 adds an option to set the clustering distance directly.

**Pull request merged**
