### PR TITLE
Add plugin support

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by caneroj1** [comment]
Hey @ericfischer,

I've only looked through this pull request a bit, but it sounds like it's possible to do arbitrary transformations on features as part of the filters. Is that correct?

It would be nice if we would be able to add the tippecanoe extension properties to features by passing them through filters.

**Comment by ericfischer** [comment]
@caneroj1 Yes, the idea is that you should be able to do arbitrary transformations.

The `layer` property from the `tippecanoe` object should work to change the layer that a feature belongs to. I'm not sure how you could change the minzoom/maxzoom dynamically since the filter is being called as each tile is already being generated.

Can you give an example of what you would like it to do?

**Comment by caneroj1** [comment]
@ericfischer I suppose that's what I would have liked to have done.

I have a lot of existing code for doing all sorts of things with each feature that I would like to call out to. For example, like handling translations, correctly generating names from other components of the feature. That stuff should all be easily doable given the current filter implementation, right?

There is also existing logic for deciding when a feature should or should not be displayed based. It would tie in nicely with the tippecanoe extensions for minzoom/maxzoom, but I want to be able to reuse that existing logic to populate the tippecanoe extension property. This is the part that you say might be difficult to do, right?

**Comment by ericfischer** [comment]
@caneroj1 When the filter is called, it is given the current zoom/x/y of the tile, so the filter can just skip feature entirely if it doesn't belong at that zoom.

Yes, you can change the properties of the feature, so you can interject translations and generate names.

**Comment by caneroj1** [comment]
@ericfischer Okay, great. That sounds like it will be just what I need then! Thanks!

I'll keep an eye out for when this reaches master.

**Comment by ericfischer** [comment]
Great! Knowing that there is a real use case for this gives me incentive to get it cleaned up and merged.

**Pull request merged**
