### PR TITLE
Don't let polygons with nonzero area disappear during cleaning

### PR DESCRIPTION
**Pull request by ericfischer**
If they collapse, turn them into placeholder squares with the
appropriate area so that there aren't visible coverage gaps.

### CODE REVIEW

**Comment by springmeyer** [comment]
Interesting. @flippmoke started throwing these out and I've also felt like this needed to be able to be an option for keeping small polys for certain visualization needs (https://github.com/mapbox/mapnik-vector-tile/issues/131). @ericfischer can you debrief more on your motivation here and what you think reasonable defaults are?

**Comment by ericfischer** [comment]
@springmeyer Tippecanoe's stated intent has always been that

> If you give it all the building footprints in Los Angeles and zoom out far enough that most individual buildings are no longer discernable, you should still be able to see the extent and variety of development in every neighborhood, not just the largest downtown buildings.

Most of the way that I have accomplished this so far is that any polygon whose area is smaller than a pixel will never be drawn directly; instead, the rounding error will be accumulated across the tile until there is at least a pixel worth of "tiny polygon" area that can all be assigned to whichever lucky tiny polygon wins the jackpot and gets to be drawn as a pixel.

This change in this PR is because it turned out that polygons with an area larger than a pixel might still decay to nothing during polygon cleaning if downsampling to the tile grid worked out badly. As the screenshot in https://github.com/mapbox/tippecanoe/issues/240 shows, this could leave large empty areas where all the polygons decayed badly in the same way, leaving no representative data.

I am not really satisfied with the shapes of the fabricated polygons in either situation. If the "tiny polygons" are adjacent, really they should be coalesced together rather than approximated with squares. But I don't know any better way to handle tiny polygons that are detached from one another, as building footprints often are. Stretching the area of the "lucky" polygon instead of drawing it as a square does not look good.

So I don't know whether this is necessarily the right policy for Mapnik, but it is the best way I've found so far to approximate a visually continuous experience from each zoom to the next.

**Comment by springmeyer** [comment]
Thank you for the explanation @ericfischer

**Comment by timiyay** [comment]
nice work @ericfischer 

Since you've cranked out a few point releases this week, could we please get a Github release for v1.11.4? I'll use it to update the Homebrew formula.

Thanks!

**Comment by ericfischer** [comment]
Thanks @timiyay! Tagged https://github.com/mapbox/tippecanoe/releases/tag/1.11.4.

**Comment by timiyay** [comment]
Thanks. The Homebrew update is in the pipeline: https://github.com/Homebrew/homebrew-core/pull/944

**Comment by ericfischer** [comment]
Thank you @timiyay!

**Pull request merged**
