### PR TITLE
Ignore error num array

### PR DESCRIPTION
**Pull request by ingalls**
This combines the branch that ignores errors with JSON number array stratification.

JSON number arrays are typically converted as `"[0,0,4.523]"`

cc/ @ericfischer

### CODE REVIEW

**Comment by ericfischer** [comment]
@ingalls What does the change to `jsonpull.c` do? If I'm reading it right, it changes from appending numbers with `string_append_string()` to appending them character by character, which I think will do the same thing but slower. Does it do something else?

**Comment by ericfischer** [comment]
Oh, or did you make the same change I made in https://github.com/mapbox/tippecanoe/commit/0e59a4f7745bd7d2ff3e9efedee03ec1c066f90f independently in a different way, and then resolve the conflict? Looks like it.

**Comment by ericfischer** [comment]
If so, I'd slightly prefer https://github.com/mapbox/tippecanoe/pull/158 (with conflicts now resolved) as slightly cleaner, but this one is OK if you like it better.

**Comment by ericfischer** [comment]
I went ahead and merged my version, but please reopen if the change to appending character by character is important.

**Comment by ingalls** [comment]
Should have added a `Don't Merge` tag. Sorry this was part of an intense night of debugging. Safe to ignore.

**Pull request closed without merging**
