### PR TITLE
Upgrade Clipper to 07b828b1 to fix self-intersecting polygons

### PR DESCRIPTION
**Pull request by ericfischer**
cc @mourner @flippmoke

### CODE REVIEW

**Comment by ericfischer** [comment]
All is not well: trying to tile `./tippecanoe -ad -z7 -f -o foo.mbtiles ne_10m_admin_0_countries.json` is getting stuck:

```
  thread #3: tid = 0x44dcb3, 0x0000000100033947 tippecanoe`ClipperLib::Clipper::FixHoleLinkage(ClipperLib::OutRec&) + 135
    frame #0: 0x0000000100033947 tippecanoe`ClipperLib::Clipper::FixHoleLinkage(ClipperLib::OutRec&) + 135
    frame #1: 0x0000000100033382 tippecanoe`ClipperLib::Clipper::BuildResult2(ClipperLib::PolyTree&) + 402
    frame #2: 0x0000000100032a9d tippecanoe`ClipperLib::Clipper::Execute(ClipperLib::ClipType, ClipperLib::PolyTree&, ClipperLib::PolyFillType, ClipperLib::PolyFillType) + 125
    frame #3: 0x0000000100032a0d tippecanoe`ClipperLib::Clipper::Execute(ClipperLib::ClipType, ClipperLib::PolyTree&, ClipperLib::PolyFillType) + 45
    frame #4: 0x0000000100021aa8 tippecanoe`clean_or_clip_poly(geom=<unavailable>, z=<unavailable>, detail=<unavailable>, buffer=<unavailable>, clip=<unavailable>) + 1656 at geometry.cc:317
    frame #5: 0x0000000100011804 tippecanoe`partial_feature_worker(v=0x00000001002b75b0) + 1284 at tile.cc:539
    frame #6: 0x00007fff8bfac05a libsystem_pthread.dylib`_pthread_body + 131
    frame #7: 0x00007fff8bfabfd7 libsystem_pthread.dylib`_pthread_start + 176
    frame #8: 0x00007fff8bfa93ed libsystem_pthread.dylib`thread_start + 13
```

**Comment by ericfischer** [comment]
Verified that it does not get stuck with Tippecanoe master (7140a3dd), only with the Clipper changes. With the old Clipper but the new optional check, it finds this self-intersection:

    Internal error: self-intersecting polygon. 1347,1950 to 1350,1952 intersects 1350,1951 to 1348,1951

**Comment by ericfischer** [comment]
In particular the United Arab Emirates is the first country where it gets stuck, at z2.

    $ head -12 ne_10m_admin_0_countries.json |  ./tippecanoe -ad -z7 -f -o foo.mbtiles

Probably the enclave within exclave at New Madha? https://gist.github.com/ericfischer/6a21e1718f9d75070fdf

screen shot 2016-03-18 at 5 20 32 pm

**Comment by ericfischer** [comment]
Yes, [the enclave is the most severe z2 self-intersection](https://gist.github.com/ericfischer/a90649c6bef96ee3bf40) if Clipper isn't allowed to clip, and tiny polygon coalescing is to blame. There is also a naturally-occurring self intersection in Abu Dhabi, but it doesn't get Clipper stuck.

**Comment by ericfischer** [comment]
Without the tiny polygon coalescing (but with new Clipper), the enclave [just gets reduced to nothing](https://gist.github.com/ericfischer/f33cfec0358938242bfc). Abu Dhabi gets pulled back to intersect at a point instead of overlapping.

**Comment by ericfischer** [comment]
Clipper 3eb6a85910aff fixes the infinite loop for Abu Dhabi, but it is still getting stuck somewhere else. Investigating…

**Comment by ericfischer** [comment]
head -192 ne_10m_admin_0_countries.json |  ./tippecanoe -ad -z7 -f -o foo.mbtiles

is what gets stuck now, in z0. (France is line 192.) But very confusing because

    head -192 ne_10m_admin_0_countries.json | tail -1 |  ./tippecanoe -ad -z7 -f -o foo.mbtiles

does work. Memory corruption that makes this feature fail only in the presence of other features?

**Comment by flippmoke** [comment]
@ericfischer If you can help me tomorrow I can dig into this more with you.

**Comment by ericfischer** [comment]
Sure, sounds good @flippmoke!

**Comment by flippmoke** [comment]
@ericfischer I would suggest to update to https://github.com/mapnik/clipper/commit/f9c1344a0976695c9899e545f90726b6c33bdd64 after the latest round of fixes

**Comment by ericfischer** [comment]
Thanks. I'll pull that in now.

**Comment by springmeyer** [comment]
@ericfischer - what is this status of this. Any hangs or crash with the latest clipper code? /cc @flippmoke

**Comment by ericfischer** [comment]
@springmeyer The status is mostly that I don't know how to fix the Travis build on Linux, which seems to be using a too-old version of libstdc++ to support the C++11 library features that Clipper now uses. I would welcome your advice on how to make it work, since all my attempts have been failing.

**Pull request merged**
