### PR TITLE
Expand tile-join functionality

### PR DESCRIPTION
**Pull request by caneroj1**
As talked about in #457, this pull request is to expand the capabilities of tile-join when filtering features in layers.

I want to get some eyes on the changes and get some feedback. There are still a few things I want to clean up and enhance, but I believe the basic functionality is essentially done.

To minimize the amount of work that had to be done, and to ensure that we handle mapbox style filters properly, I pulled in some more code from mapbox gl native from revision f2c9f2b.

Summary of changes:
- tile-join will accept a `-j` parameter that is a path to a json file. The file's contents could look like:
```
{
  "layers": [
    {
      "id": "in",
      "filter": [
        "==",
        "scalerank",
        3
      ]
    }
  ]
}
```
- we parse that file as part of start up for tile-join and construct a `std::map` b/w a layer name and a `mbgl::style::Filter` object.
- whenever we encounter a layer that has a filter in our map, we use the associated `mbgl::style::Filter` object to determine which features should remain. I put this step as late in the process as I thought appropriate.

Let me know what you think.

### CODE REVIEW

**Comment by ericfischer** [comment]
Thanks for the contribution!

I am kind of overwhelmed by the amount of code that it adds to do the filtering though. I think it may be better to do the filtering within the facilities that Tippecanoe already uses instead of pulling in another JSON parser and so much code from Mapbox GL.

So I've tried another implementation of a slightly simplified version of your filter syntax in https://github.com/mapbox/tippecanoe/pull/462. It needs some more testing but seems to work. Do you think that version will do what you are looking for?

**Comment by caneroj1** [comment]
No problem!

I was overwhelmed, as well. My intent was to not rewrite any of the existing logic for parsing and evaluating filters, but it turned out to be a ton of code.

This seems fine though, and as long as the filter syntax is the same (which it seems to be), then this should work for what I need.

I'll take a closer look and try it out, too, if that would be helpful.

**Comment by ericfischer** [comment]
Yes, please give it a try and let me know if you see any problems!

**Comment by caneroj1** [comment]
Hey @ericfischer,

I tested this out on a large dataset with a few filters and it seems to be working just fine.

**Comment by ericfischer** [comment]
Great! I am going to close this PR, then, and merge the other branch after adding a few more tests.

**Pull request closed without merging**
