### PR TITLE
Encode numeric attributes as integers instead of floating point if possible

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by springmeyer** [comment]
@ericfischer - I've considered trying this optimization in mapnik-vector-tile as well, but hesitated for fear of breaking applications that might be expecting consistent type storage for a given field across tiles. But that is theoretical and I've not written or encountered this in practice. So, can you think of any pitfalls with this or are you confidence it should be compatible across use-cases? /cc @flippmoke

**Comment by ericfischer** [comment]
@springmeyer Maybe this was a bad idea. Coercing numberlike strings to numbers as was being discussed for address nodes scares me, but since the TileJSON metadata doesn't distinguish between numeric types but always just says "Number" I thought renderers treated all numeric types as interchangeable. I'll roll this back if you think it's dangerous.

**Comment by buma** [comment]
Maybe you could use number only in tags which are always number:
- unit
- way id
- changeset
- timestamp
- version
And the rest are strings (like it is now I think.)

**Comment by ericfischer** [comment]
@buma Good point. I can't really make assumptions about types based on the names of the fields, but I do have complete access to the data as I am reading it, so I could be consistent and use integers only for the fields that always contain an integer.

**Comment by springmeyer** [comment]
@ericfischer - I propose keeping this change and watching closely for breakages. I'm not proposing rolling it back without evidence of any problems.

**Comment by springmeyer** [comment]
@ericfischer - would also love to see from you some representative #'s for space savings you are seeing from this.

**Comment by ericfischer** [comment]
@springmeyer My main test was Natural Earth countries to z3, where it was about a 1% savings (1040384 bytes vs 1052672). Precision for large numbers seems to be more compelling than the size reduction.

**Comment by aaronlidman** [comment]
@ericfischer - Can you tag a release for this so we can use it downstream in the QA Tiles?

**Comment by ericfischer** [comment]
Sure @aaronlidman. Tagged as [1.4.3](https://github.com/mapbox/tippecanoe/releases/tag/1.4.3) now.

**Comment by springmeyer** [comment]
> Precision for large numbers seems to be more compelling than the size reduction.

@ericfischer - say more about this?

**Comment by springmeyer** [comment]
@ericfischer oh, nvm, I see now https://github.com/osmlab/osm-qa-tiles/issues/5

**Pull request merged**
