### PR TITLE
Add input support for CSV file format

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by mapsam** [comment]
This is great @ericfischer! Thanks for rocking on this. Let me know if you'd like any extra 👀

**Comment by ericfischer** [comment]
Thanks @mapsam!

The thing I am kind of stuck on is knowing exactly what set of CSV-like formats need to be supported. There are a huge variety of them in https://github.com/mapnik/test-data/tree/master/csv and it is unclear to me where Mapnik's code to parse them is, where these tests are run, and which formats are actually used in practice.

Alternately, let me know if you want me to just go ahead and get it released with the current support for only fairly normal CSV files.

**Comment by mapsam** [comment]
That's a good question - assuming you're only handling point CSVs, I think just having a relatively robust set of latitude and longitude string alternatives (i.e. lng vs. lon vs. long) would be beneficial. So I'm 👍 on releasing for normal CSVs and getting a sense of what users may want supported in the future as they try it out.

**Comment by ericfischer** [comment]
Great, I'll add a test for the simple point case then, and only worry about WKT and other quoting conventions if it comes up later. It should already accept the same column name variations that Mapnik does.

**Comment by mapsam** [comment]
🎉

**Comment by mfisher35** [comment]
Hi all, any chance of getting MULTIPOLYGON/MULTILINESTRING support as well? converting CSVs to GeoJSON takes a super long time due to it's repetitiveness (i.e. every value is required to include the category/column name)

**Comment by ericfischer** [comment]
That would probably be a useful feature and I would be happy to accept a patch to add WKT support.

**Comment by JivanRoquet** [comment]
Is there a documentation on how to use the CSV file format with tippecanoe? (which column names, etc)

**Pull request merged**
