### PR TITLE
Don't accept features or geometries inside another object's properties

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by nhoover** [comment]
Is this going to be merged? Would really like this fix! Thanks!

**Comment by ericfischer** [comment]
I haven't merged it because it breaks the `geobuf` tests. I need to reconcile the GeoJSON parsing in `tippecanoe-json-tool` with that in `tippecanoe` proper before I can properly release it.

**Comment by ericfischer** [comment]
This should be fixed for real in https://github.com/mapbox/tippecanoe/pull/627

**Comment by nhoover** [comment]
Thanks!

**Pull request closed without merging**
